# Generated by Django 4.2 on 2024-07-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('document', models.CharField(max_length=200)),
                ('document_type', models.CharField(max_length=5, null=True)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('task_status', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=200)),
                ('delivery_date', models.CharField(max_length=200)),
                ('commentary', models.CharField(max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_task.person')),
            ],
        ),
    ]
