# Generated by Django 4.2 on 2024-07-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_task', '0002_alter_task_priority_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='delivery_date',
            field=models.DateField(max_length=200),
        ),
    ]
